swagger: "2.0"
info:
  description: "This API is used to get today order or get order by order id"
  version: "v1"
  title: "Get Today Order"
paths:
  /v1/trade/order/today:
    get:
      access: "Trading Permissions"
      parameters:
        - name: "symbol"
          type: "string"
          in: query
          description: "Stock symbol, use `ticker.region` format, example: `AAPL.US`"
          required: false
        - name: "status"
          type: string[]
          in: query
          description: "[Order status](../trade-definition#orderstatus)<br/><br/>example: `status=FilledStatus&status=NewStatus`"
          required: false
        - name: side
          type: "string"
          in: query
          description: Order side<br/><br/>
            **Enum Value:**<br/>
            `Buy`<br/>
            `Sell`
          required: false
        - name: market
          type: "string"
          in: query
          description: Market<br/><br/>
            **Enum Value:**<br/>
            `US` - United States of America Market<br/>
            `HK` - Hong Kong Market
          required: false
        - name: "order_id"
          type: "string"
          required: false
          description: "Order ID, example: `701276261045858304`"
      responses:
        "200":
          description: "Get Today Orders Success"
          schema:
            $ref: "#/definitions/today_orders_rsp"
        "400":
          description: "The query failed with an error in the request parameter."
      request_body:
        type: "python"
        value: |
          import os
          import json
          from longbridge.http import Auth, Config, HttpClient

          auth = Auth(os.getenv("LONGBRIDGE_APP_KEY"), os.getenv("LONGBRIDGE_APP_SECRET"), access_token=os.getenv("LONGBRIDGE_ACCESS_TOKEN"))
          http = HttpClient(auth, Config(base_url="https://openapi.longbridgeapp.com"))

          query = {
            'symbol': '700.HK',
            'status': ['FilledStatus', 'NewStatus'],
            'side': 'Buy',
            'market': 'HK',
          }

          resp = http.get("/v1/trade/order/today", query)
          print(json.dumps(resp.data, indent=2))
      response_body:
        {
          "code": 0,
          "message": "success",
          "data":
            {
              "orders":
                [
                  {
                    "currency": "HKD",
                    "executed_price": "0.000",
                    "executed_quantity": "0",
                    "expire_date": "",
                    "last_done": "",
                    "limit_offset": "",
                    "msg": "",
                    "order_id": "706388312699592704",
                    "order_type": "ELO",
                    "outside_rth": "UnknownOutsideRth",
                    "price": "11.900",
                    "quantity": "200",
                    "side": "Buy",
                    "status": "RejectedStatus",
                    "stock_name": "Bank of East Asia Ltd/The",
                    "submitted_at": "1651644897",
                    "symbol": "23.HK",
                    "tag": "Normal",
                    "time_in_force": "Day",
                    "trailing_amount": "",
                    "trailing_percent": "",
                    "trigger_at": "0",
                    "trigger_price": "",
                    "trigger_status": "NOT_USED",
                    "updated_at": "1651644898",
                  },
                ],
            },
        }
definitions:
  today_orders_rsp:
    properties:
      orders:
        type: "object[]"
        description: Order Detail
        required:
          [
            "order_id",
            "status",
            "stock_name",
            "quantity",
            "submitted_at",
            "side",
            "symbol",
            "order_type",
            "tag",
            "time_in_force",
            "currency",
          ]
        properties:
          order_id:
            type: "string"
            description: Order ID
            required: true
          status:
            type: "string"
            description: "[Order Status](../trade-definition#orderstatus)"
            required: true
          stock_name:
            type: "string"
            description: Stock Name
            required: true
          quantity:
            type: "string"
            description: Submitted Quantity
            required: true
          executed_quantity:
            type: "string"
            description: Executed Quantity
          price:
            type: "string"
            description: Submitted Price
          executed_price:
            type: "string"
            description: Executed Price
          submitted_at:
            type: "string"
            description: Submitted Time
            required: true
          side:
            type: "string"
            description: Order Side<br/><br/>
              **Enum Value:**<br/>
              `Buy`<br/>
              `Sell`
            required: true
          symbol:
            type: "string"
            description: "Stock symbol, use `ticker.region` format, example: `AAPL.US`"
            required: true
          order_type:
            type: "string"
            description: "[Order Type](../trade-definition#ordertype)"
            required: true
          last_done:
            type: "string"
            description: Last done
          trigger_price:
            type: "string"
            description: "`LIT` / `MIT` Order Trigger Price"
          msg:
            type: "string"
            description: Rejected Message Or Remark
          tag:
            type: "string"
            description: Order tag<br/><br/>
              **Enum Value**<br/>
              `Normal` - Normal Order<br/>
              `GTC` - Long term Order<br/>
              `Grey` - Grey Order
            required: true
          time_in_force:
            type: "string"
            description: "
              Time in force Type<br/><br/>
              **Enum Value:**<br/>
              `Day` - Day Order<br/>
              `GTC` - Good Til Canceled Order<br/>
              `GTD` - Good Til Date Order"
            required: true
          expire_date:
            type: "string"
            description: "Long term order expire date, format: `YYYY-MM-DD`, example: `2022-12-05`"
          updated_at:
            type: "string"
            description: Last updated time, formatted as a timestamp (second)
          trigger_at:
            type: "string"
            description: Conditional order trigger time. formatted as a timestamp (second)
          trailing_amount:
            type: "string"
            description: "`TSMAMT` / `TSLPAMT` order trailing amount"
          trailing_percent:
            type: "string"
            description: "`TSMPCT` / `TSLPPCT` order trailing percent"
          limit_offset:
            type: "string"
            description: "`TSLPAMT` / `TSLPPCT` order limit offset amount"
          trigger_status:
            type: "string"
            description: Conditional Order Trigger Status<br/><br/>
              **Enum Value**<br/>
              `NOT_USED`<br/>
              `DEACTIVE`<br />
              `ACTIVE`<br />
              `RELEASED`
          currency:
            type: "string"
            description: Currency
            required: true
          outside_rth:
            type: "string"
            description:
              Enable or disable outside regular trading hours<br/><br/>
              **Enum Value:**<br/>
              `RTH_ONLY` - Regular trading hour only<br/>
              `ANY_TIME` - Any time"
