swagger: "2.0"
info:
  description: "該接口用於獲取歷史訂單"
  version: "v1"
  title: "獲取歷史訂單"
paths:
  /v1/trade/order/history:
    get:
      access: "交易權限"
      parameters:
        - name: "symbol"
          type: "string"
          in: query
          description: "股票代碼，使用 `ticker.region` 格式，例如：`AAPL.US`"
          required: false
        - name: "status"
          type: string[]
          in: query
          description: "[訂單狀態](../trade-definition#orderstatus)<br/><br/>例如: `status=FilledStatus&status=NewStatus`"
          required: false
        - name: side
          type: "string"
          in: query
          description: "
            買賣方向<br/><br/>
            **可選值:**<br/>
            `Buy` - 買入<br/>
            `Sell` - 賣出"
          required: false
        - name: market
          type: "string"
          in: query
          description: "
            市場<br/><br/>
            **可選值:**<br/>
            `US` - 美股<br/>
            `HK` - 港股"
          required: false
        - name: "start_at"
          type: "string"
          required: false
          description: "開始時間，格式為時間戳 (秒)，例如: `1650410999`"
        - name: "end_at"
          type: "string"
          required: false
          description: "結束時間，格式為時間戳 (秒)，例如: `1650410999`"
      responses:
        "200":
          description: "歷史訂單查詢成功"
          schema:
            $ref: "#/definitions/history_orders_rsp"
        "400":
          description: "查詢失敗，請求參數錯誤。"
      request_body:
        type: "python"
        value: |
          import os
          import json
          from longbridge.http import Auth, Config, HttpClient

          auth = Auth(os.getenv("LONGBRIDGE_APP_KEY"), os.getenv("LONGBRIDGE_APP_SECRET"), access_token=os.getenv("LONGBRIDGE_ACCESS_TOKEN"))
          http = HttpClient(auth, Config(base_url="https://openapi.longbridgeapp.com"))

          query = {
            'symbol': '700.HK',
            'status': ['FilledStatus', 'NewStatus'],
            'side': 'Buy',
            'market': 'HK',
            'start_at': '1652111483',
            'end_at': '1652321483',
          }

          resp = http.get("/v1/trade/order/history", query)
          print(json.dumps(resp.data, indent=2))
      response_body:
        {
          "code": 0,
          "message": "success",
          "data":
            {
              "orders":
                [
                  {
                    "currency": "HKD",
                    "executed_price": "0.000",
                    "executed_quantity": "0",
                    "expire_date": "",
                    "last_done": "",
                    "limit_offset": "",
                    "msg": "",
                    "order_id": "706388312699592704",
                    "order_type": "ELO",
                    "outside_rth": "UnknownOutsideRth",
                    "price": "11.900",
                    "quantity": "200",
                    "side": "Buy",
                    "status": "RejectedStatus",
                    "stock_name": "東亞銀行",
                    "submitted_at": "1651644897",
                    "symbol": "23.HK",
                    "tag": "Normal",
                    "time_in_force": "Day",
                    "trailing_amount": "",
                    "trailing_percent": "",
                    "trigger_at": "0",
                    "trigger_price": "",
                    "trigger_status": "NOT_USED",
                    "updated_at": "1651644898",
                  },
                ],
            },
        }
definitions:
  history_orders_rsp:
    required: ["has_more"]
    properties:
      has_more:
        type: boolean
        description: "是否還有更多數據"
        required: true
      orders:
        type: "object[]"
        description: 訂單信息
        required:
          [
            "order_id",
            "status",
            "stock_name",
            "quantity",
            "submitted_at",
            "side",
            "symbol",
            "order_type",
            "tag",
            "time_in_force",
            "currency",
          ]
        properties:
          order_id:
            type: "string"
            description: 訂單 ID
            required: true
          status:
            type: "string"
            description: "[訂單狀態](../trade-definition#orderstatus)"
            required: true
          stock_name:
            type: "string"
            description: 股票名稱
            required: true
          quantity:
            type: "string"
            description: 下單數量
            required: true
          executed_quantity:
            type: "string"
            description: 成交數量
          price:
            type: "string"
            description: 下單價格
          executed_price:
            type: "string"
            description: 成交價格
          submitted_at:
            type: "string"
            description: 下單時間
            required: true
          side:
            type: "string"
            description: "
              買賣方向<br/><br/>
              **可選值:**<br/>
              `Buy` - 買入<br/>
              `Sell` - 賣出"
            required: true
          symbol:
            type: "string"
            description: "股票代碼，使用 `ticker.region` 格式，例如：`AAPL.US`"
            required: true
          order_type:
            type: "string"
            description: "[訂單類型](../trade-definition#ordertype)"
            required: true
          last_done:
            type: "string"
            description: 最近成交價格
          trigger_price:
            type: "string"
            description: "`LIT` / `MIT` 訂單觸發價格"
          msg:
            type: "string"
            description: 拒絕信息或備註
          tag:
            type: "string"
            description: "訂單標記<br/><br/>
              **可選值:**<br/>
              `Normal` - 普通訂單<br/>
              `GTC` - 長期單<br/>
              `Grey` - 暗盤單"
            required: true
          time_in_force:
            type: "string"
            description: "
              訂單有效期類型<br/><br/>
              **可選值:**<br/>
              `Day` - 當日有效<br/>
              `GTC` - 撤單前有效<br/>
              `GTD` - 到期前有效"
            required: true
          expire_date:
            type: "string"
            description: 長期單過期時間，格式為 `YYYY-MM-DD`, 例如：`2022-12-05`
          updated_at:
            type: "string"
            description: 最近更新時間，格式為時間戳 (秒)
          trigger_at:
            type: "string"
            description: 條件單觸發時間，格式為時間戳 (秒)
          trailing_amount:
            type: "string"
            description: "`TSLPAMT` / `TSMAMT` 訂單跟蹤金額"
          trailing_percent:
            type: "string"
            description: "`TSLPPCT` / `TSMAPCT` 訂單跟蹤漲跌幅"
          limit_offset:
            type: "string"
            description: "`TSLPAMT` / `TSLPPCT` 訂單指定價差"
          trigger_status:
            type: "string"
            description: "條件單觸發狀態<br/><br/>
              **可選值:**<br/>
              `NOT_USED` - 未激活
              `DEACTIVE` - 已失效
              `ACTIVE` - 已激活
              `RELEASED` - 已觸發"
          currency:
            type: "string"
            description: 結算貨幣
            required: true
          outside_rth:
            type: "string"
            description: 是否允許盤前盤後<br/><br/>
              **可選值:**<br/>
              `RTH_ONLY` - 不允許盤前盤後<br/>
              `ANY_TIME` - 允許盤前盤後"
