swagger: "2.0"
info:
  description: "订单接口介111绍"
  version: "v1"
  title: "订单"
host: "openapi.longbridge.sg"
basePath: "/api/v1"
tags:
  - name: "订单"
    description: "订单接口介绍"
    externalDocs:
      description: "需要时添加这部分内容"
      url: "http://open.longbridgeapp.com/docs/order_detail"

paths:
  /trade/orders/submit:
    post:
      tags:
        - "订单"
      summary: "下单概述"
      description: "港美股，窝轮，期权委托下单"
      consumes:
        - "application/json"
      produces:
        - "application/json"
      parameters:
        - in: "body"
          name: "body"
          description: "create order"
          required: true
          schema:
            $ref: "#/definitions/CreateOrder"
      responses:
        "200":
          description: "订单已委托"
        "401":
          description: "下单被拒绝，资金不足。"

  /trade/orders/replace:
    post:
      tags:
        - "订单"
      summary: "修改订单的价格和数量等"
      description: "修改订单的价格和数量等,[权限](https://open.longbridgeapp.com/docs/auth)"
      operationId: "orderID"
      consumes:
        - "application/json"
      produces:
        - "application/json"
      parameters:
        - in: "body"
          name: "body"
          description: "replace order"
          required: true
          schema:
            $ref: "#/definitions/ReplaceOrder"
      responses:
        "200":
          description: "订单已委托"
        "401":
          description: "下单被拒绝，资金不足。"


definitions:
  ReplaceOrder:
    type: "object"
    properties:
      quantity:
        type: "integer"
        format: "int32"
      price:
        type: "integer"
        format: "float"
        default: 100.92
      id:
        type: "integer"
        format: "float"
        default: 1
  CreateOrder:
    type: "object"
    properties:
      quantity:
        type: "integer"
        format: "int32"
      price:
        type: "integer"
        format: "float"
        default: 100.92
