name: Build canary env

on:
  pull_request:
    branches:
      - canary
jobs:
  build:
    name: Build canary
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: yarn
      - name: Installation
        run: yarn
      - name: Build docs
        run: |
          yarn build --locale zh-CN
          ls ./dist/
          ls ./dist/canary
          
